name: Deploy play.metaculus.com (Experiments)

on:
  workflow_dispatch:

jobs:
  deploy-to-play:
    runs-on: ubuntu-22.04
    environment: play_env
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: play-metaculus-web
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NEXT_PUBLIC_DISALLOW_ALL_BOTS: ${{ vars.NEXT_PUBLIC_DISALLOW_ALL_BOTS }}
      NEXT_PUBLIC_CDN_DOMAIN_NAME: ${{ vars.NEXT_PUBLIC_CDN_DOMAIN_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and deploy to Heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku container:login # uses the HEROKU_API_KEY
          ./scripts/deploy_to_heroku.sh
