name: Deploy metaculus.com (PRODUCTION)

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-22.04
    environment: prod_env
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: metaculus-web
      NEXT_PUBLIC_APP_URL: "https://www.metaculus.com"
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and deploy to Heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku container:login # uses the HEROKU_API_KEY
          ./scripts/deploy_to_heroku.sh
